@protocol = http
@domain = localhost
@port = 5000
@host = {{protocol}}://{{domain}}:{{port}}

##########################################################
# @name codeGrant

POST {{host}}/loginCodeGrant
Content-Type: application/json


{
    "email": "test@gmail.com",
    "password": "test"
}

##########################################################
# @name implicitGrant

POST {{host}}/loginImplicitGrant
Content-Type: application/json


{
    "email": "test@gmail.com",
    "password": "test"
}